### ISSUE TITLE
CFI methods to update objects

### ISSUE THREAD

**Issue by donpdonp** [ChromaPDX/issues#6]
Each of the collections in the CFI app need to have open asset related fields updated.

updateCampaign()
- oa_address
- oa_asset_id

updateOrder()
- oa_tx_id

updateUser()
- oa_address

I dont have a sense of whether to allow the methods to update the entire object at once, or if specific setter methods are better such as updateCampaignOaAddress(campaign_id, new_oa_address).

**Comment by adamwong246** [comment]
https://bitbucket.org/adamwong246/chroma-fund/pull-request/1/add-updatecampaign-and-updateorder-and/diff
